version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - echo Build started
      - gradle clean jar
      - echo Build completed
  post_build:
    commands:
      - aws cloudformation package --template-file samTemplate.yml --s3-bucket ianapriazhkinabucket --output-template-file outputSamTemplate.yml
artifacts:
  files:
    - build/libs/*.jar
    - outputSamTemplate.yml